//==================================================================================
//==================================================================================
// File: FlasherLoader.cpp
// Description: Centralized initialization and management
//              hardware resources and software components (TFT display, GUI,
//              DSP modules, etc.)
//
// Copyright (c) 2025-2026 DadDesign-Project.
//==================================================================================
//==================================================================================

#include "main.h"
#include "PersistentDefine.h"
#include "options.h"
#include "Sections.h"
#include "cLoaderTarget.hpp"


//**********************************************************************************
// External handles (generated by CubeMX)
//**********************************************************************************
extern QSPI_HandleTypeDef hqspi;               // QSPI flash interface handle
extern SAI_HandleTypeDef  hsai_BlockA1;        // SAI block A1 for audio
extern SAI_HandleTypeDef  hsai_BlockB1;        // SAI block B1 for audio
extern DMA_HandleTypeDef  hdma_sai1_a;         // DMA for SAI A
extern DMA_HandleTypeDef  hdma_sai1_b;         // DMA for SAI B
extern SPI_HandleTypeDef  hspi1;               // SPI for display
extern DMA_HandleTypeDef  hdma_spi1_tx;        // DMA for SPI transmit
extern UART_HandleTypeDef huart1;              // UART for MIDI
extern DMA_HandleTypeDef  hdma_usart1_rx;      // DMA for UART receive
extern TIM_HandleTypeDef  htim6;

//**********************************************************************************
// Global instances
//**********************************************************************************

// SDRAM
#include "AS4C16M32SB.h"

// Flash memory instance
#include "IS25LP064A.h"
DadDrivers::cIS25LP064A __Flash;

// Persistent storage instances
#include "cFlasherStorage.h"
QFLASH_FLASHER  DadPersistentStorage::cFlasherStorage __FlasherStorage;
#include "cBlockStorageManager.h"
QFLASH_TABSAVE  uint8_t      						  __TabSaveBlock[BLOCK_STORAGE_MEM_SIZE];
DadPersistentStorage::cBlockStorageManager            __BlockStorageManager(__TabSaveBlock);
#include "cFlasherClient.h"
DadPersistentStorage::cFlasherClient 				  __FlasherClient;

// -------------------------------------------------------------------
// Persistent Target — reserved in QFLASH_LOADER flash section
//QFLASH_LOADER uint8_t __LoaderInfo[QFLAH_SECTOR_SIZE];

// Display instance
#include "cDisplay.h"
DECLARE_DISPLAY(__Display);
#include "Font_10p.h"
#include "Font_12p.h"
#include "Font_14p.h"
#include "Font_16p.h"
#include "Font_24pb.h"

// Switch instances
#include "cSwitch.h"
DadDrivers::cSwitch __Switch1;
DadDrivers::cSwitch __Switch2;

// Encoder instances
#include "cEncoder.h"
DadDrivers::cEncoder __Encoder1;
DadDrivers::cEncoder __Encoder2;
DadDrivers::cEncoder __Encoder3;
DadDrivers::cEncoder __Encoder0;

// MPU Config
extern void MPU_Config(void);

// Target ELF Loader
cLoaderTarget	__LoaderMemTarget;
uint8_t			__NbELF_File;
uint16_t 		__TabELF_File[DIR_FILE_COUNT];

//**********************************************************************************
// HAL_TIM_PeriodElapsedCallback
// Timer interrupt callback for Encoder Debounce
//**********************************************************************************
extern "C" void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {
  if (htim->Instance == TIM6) {
	__Encoder0.Debounce();
  }
}

// ===================================================================
// Description : Loads an application executable and jumps to it.
//
// This function retrieves the ELF regions from the persistent storage,
// copies the data and zero-initialized segments to the target memory
// addresses, writes a magic word to signal the startup code, and resets
// the microcontroller to execute the new application.
//
// The name (or path) of the ELF file to load.
//
static void loadRegionsAndJump(const char *pName){

    DadPersistentStorage::sRegionInfo* pRegion;
    uint32_t nbRegions;
    uint8_t* FilePtr;

    if(false == __FlasherStorage.GetElfRegionsInformation(pName, FilePtr, pRegion, nbRegions)){
        while(1);
    }

    // Save the 3 C parameters into D3 scratch SRAM before entering
    // the register-constrained asm block — avoids GCC "impossible constraints"
    // D3 scratch layout (16 bytes at 0x38001000):
    //   +0x00 : pRegion   (base pointer to region array)
    //   +0x04 : nbRegions (total region count)
    //   +0x08 : FilePtr   (base address of ELF file in storage)
    //   +0x0C : i         (loop index, initialized to 0)
    volatile uint32_t* pD3 = (volatile uint32_t*)0x38001000;
    pD3[0] = (uint32_t)pRegion;
    pD3[1] = (uint32_t)nbRegions;
    pD3[2] = (uint32_t)FilePtr;
    pD3[3] = 0;  // i = 0

    // From this point: pure assembly, no stack/heap usage
    // All working variables are read from D3 scratch only
    __asm volatile (

		/* ── 1. Disable all interrupts before the copy loop ────────────── */
		"CPSID   IF                        \n" // Set PRIMASK=1 and FAULTMASK=1

		/* Also disable SysTick to prevent any timer preemption */
		"LDR     r4,  =0xE000E010          \n" // SysTick->CTRL address
		"LDR     r5,  [r4]                 \n"
		"BIC     r5,  r5,  #1              \n" // Clear ENABLE bit
		"STR     r5,  [r4]                 \n"

		/* ── 2. Main region loop ────────────────────────────────────────── */
	"loop_start:                           \n"
		"LDR     r4,  =0x38001000          \n" // r4 = D3 scratch base
		"LDR     r0,  [r4, #12]            \n" // r0 = i
		"LDR     r1,  [r4, #4]             \n" // r1 = nbRegions
		"CMP     r0,  r1                   \n"
		"BGE     loop_end                  \n" // i >= nbRegions → exit loop

		/* Compute pointer to current region: base + i * sizeof(sRegionInfo) */
		/* sizeof(sRegionInfo) = 5 * 4 = 20 bytes                            */
		"LDR     r2,  [r4, #0]             \n" // r2 = pRegion base
		"MOV     r3,  #20                  \n" // sizeof(sRegionInfo)
		"MLA     r2,  r0, r3, r2           \n" // r2 = &pRegion[i]

		/* Load sRegionInfo fields individually (r7 never used) */
		"LDR     r5,  [r2, #0]             \n" // r5  = file_offset
		"LDR     r6,  [r2, #4]             \n" // r6  = dest_addr
		"LDR     r10, [r2, #8]             \n" // r10 = source_addr
		"LDR     r11, [r2, #12]            \n" // r11 = copy_size
		"LDR     r12, [r2, #16]            \n" // r12 = zero_size

		/* ── 2a. Skip regions at or above 0x38010000 (bootloader reserved) */
		"LDR     r3,  =0x38010000          \n"
		"CMP     r6,  r3                   \n" // compare dest_addr
		"BGE     loop_next                 \n" // dest_addr >= limit → skip

		/* ── 2b. Copy phase (copy_size > 0) ────────────────────────────── */
		"CMP     r11, #0                   \n" // CBZ only works on r0-r7,
		"BEQ     skip_copy                 \n" // so use CMP+BEQ for r11

		/* Select effective destination:
		   if source_addr != dest_addr → copy to source_addr
		   if source_addr == dest_addr → copy to dest_addr   */
		"CMP     r10, r6                   \n"
		"ITE     NE                        \n"
		"MOVNE   r3,  r10                  \n" // effective dest = source_addr
		"MOVEQ   r3,  r6                   \n" // effective dest = dest_addr

		/* Source in file: FilePtr + file_offset */
		"LDR     r0,  [r4, #8]             \n" // FilePtr from D3 scratch
		"ADD     r0,  r0,  r5              \n" // r0 = FilePtr + file_offset

		/* Byte-by-byte copy — no stack dependency, safe across RAM regions */
		/* r3 = dst, r0 = src, r11 = byte count                             */
	"copy_loop:                            \n"
		"CMP     r11, #0                   \n"
		"BEQ     skip_copy                 \n"
		"LDRB    r5,  [r0],  #1            \n" // load byte from source, post-increment
		"STRB    r5,  [r3],  #1            \n" // store byte to dest,   post-increment
		"SUBS    r11, r11,  #1             \n"
		"B       copy_loop                 \n"

	"skip_copy:                            \n"
		/* Reload struct pointer and fields after copy loop consumed registers */
		"LDR     r4,  =0x38001000          \n"
		"LDR     r1,  [r4, #12]            \n" // i
		"LDR     r2,  [r4, #0]             \n" // pRegion base
		"MOV     r3,  #20                  \n"
		"MLA     r2,  r1, r3, r2           \n" // r2 = &pRegion[i] again
		"LDR     r6,  [r2, #4]             \n" // r6  = dest_addr
		"LDR     r11, [r2, #12]            \n" // r11 = copy_size
		"LDR     r12, [r2, #16]            \n" // r12 = zero_size

		/* ── 2c. Zero phase (zero_size > 0) ────────────────────────────── */
		"CMP     r12, #0                   \n" // CBZ only works on r0-r7,
		"BEQ     loop_next                 \n" // so use CMP+BEQ for r12

		/* Zero area starts at: dest_addr + copy_size */
		"ADD     r3,  r6,  r11             \n" // r3 = dest_addr + copy_size
		"MOV     r0,  #0                   \n"
	"zero_loop:                            \n"
		"CMP     r12, #0                   \n"
		"BEQ     loop_next                 \n"
		"STRB    r0,  [r3],  #1            \n" // write zero byte, post-increment
		"SUBS    r12, r12,  #1             \n"
		"B       zero_loop                 \n"

	"loop_next:                            \n"
		/* Increment loop index i in D3 scratch */
		"LDR     r4,  =0x38001000          \n"
		"LDR     r0,  [r4, #12]            \n"
		"ADD     r0,  r0,  #1              \n"
		"STR     r0,  [r4, #12]            \n"
		"B       loop_start                \n"

		/* ── 3. Write magic word to D3 base to signal readiness ─────────── */
	"loop_end:                             \n"
		"LDR     r4,  =0x38000000          \n"
		"LDR     r5,  =0xBAD02850          \n"
		"STR     r5,  [r4]                 \n" // *0x38000000 = 0xBAD02850

		/* ── 4. Memory and instruction barriers before reset ────────────── */
		"DSB                               \n" // ensure all writes are committed
		"ISB                               \n" // flush instruction pipeline

		/* ── 5. System reset via SCB->AIRCR (NVIC_SystemReset equivalent) ─ */
		"LDR     r4,  =0xE000ED0C          \n" // SCB->AIRCR
		"LDR     r5,  =0x05FA0004          \n" // VECTKEY | SYSRESETREQ
		"STR     r5,  [r4]                 \n"

		/* Should never be reached */
	"spin:                                 \n"
		"B       spin                      \n"

		:                                      // no outputs
		:                                      // no inputs — everything via D3 scratch
		: "r0","r1","r2","r3","r4","r5","r6","r10","r11","r12","memory","cc"
	);
}

// ===================================================================
// Description : Scan the storage directory to identify all ELF files
//               and build an index table of available executable files.
//
// Notes       : - __NbELF_File is reset before scanning
//               - Each ELF file index is stored in __TabELF_File
//               - Only files with type FILE_TYPE_ELF are selected
//
static void scanELF_File(){
	__NbELF_File = 0; // Reset ELF file counter

	for(uint16_t Index = 0; Index < DIR_FILE_COUNT; Index++){
		// Check if the current file is an ELF executable
		if(__FlasherStorage.GetFileType(Index) == DadPersistentStorage::FILE_TYPE_ELF){
			__TabELF_File[__NbELF_File] = Index; // Store file index
			__NbELF_File++;                      // Increment ELF file count
		}
	}
}

#define SCREEN_WIDTH        320     // Total screen width in pixels
#define SCREEN_HEIGHT       240     // Total screen height in pixels

#define FLASHER_PANEL_HEIGHT 95
#define LOADER_PANEL_HEIGHT 129
#define INFO_FLASHER_HEIGHT 50
#define BLOC_FLASHER_HEIGHT 50
#define TARGET_LOADER_HEIGHT 50
#define CHOICE_LOADER_HEIGHT 50

#define Y_TITRE_FLASHER 6
#define Y_INFO_FLASHER 18
#define Y_BLOC_FLASHER 49

#define Y_LOADER_PANEL 105
#define Y_TITRE_LOADER  107
#define Y_TARGET_LOADER 116
#define Y_CHOICE_LOADER 142
#define Y_HELP_LOADER  173


DECLARE_LAYER(MainLayer, SCREEN_WIDTH, SCREEN_HEIGHT);
DECLARE_LAYER(InfoLayer, SCREEN_WIDTH, INFO_FLASHER_HEIGHT);
DECLARE_LAYER(BlocInfoLayer, SCREEN_WIDTH, BLOC_FLASHER_HEIGHT);
DECLARE_LAYER(TargetLayer, SCREEN_WIDTH, TARGET_LOADER_HEIGHT);
DECLARE_LAYER(ChoiceLayer, SCREEN_WIDTH, CHOICE_LOADER_HEIGHT);

//**********************************************************************************
// HardwareAndCoInitialize
// Initializes all hardware peripherals in the correct order
//**********************************************************************************
void MainFlasherLoader() {

    // Initialize SDRAM memory
	AS4C16M32SB_Initialize();

    // Initialize QSPI flash memory
    if (HAL_OK != __Flash.Init(&hqspi, DOUBLE_MODE, FLASH_ADDRESS)) {
        Error_Handler();
    }

    // -------------------------------------------------------------------
    // Wait 2 seconds to Switch 0 is activated
    uint32_t tickStart = HAL_GetTick();
    bool  FlasherOn = false;

    while ((HAL_GetTick() - tickStart) < 2000) {
        if (HAL_GPIO_ReadPin(FootSwitch2_GPIO_Port, FootSwitch2_Pin) == GPIO_PIN_RESET)
        {
      	  FlasherOn = true;
      	  break;
        }
    }
    // If switch 0 is activated load effect
    if(FlasherOn == false){
		const char *pName = __FlasherStorage.GetFileName(__LoaderMemTarget.load());
		if(pName){
			loadRegionsAndJump(pName);
		}
    }

    // Configure Memory Protection Unit
    //MPU_Config();

    // Invalidate CPU caches for memory consistency
    //SCB_InvalidateDCache();
    //SCB_InvalidateICache();

    // Initialize rotary encoders
    constexpr uint32_t EncoderUpdatePeriodMs = 10; // 1ms update
    constexpr uint32_t SwitchUpdatePeriodMs  = 50; // 5ms switch check

    __Encoder0.Init(Encoder0_A_GPIO_Port, Encoder0_A_Pin,
                    Encoder0_B_GPIO_Port, Encoder0_B_Pin,
                    Encoder0_SW_GPIO_Port, Encoder0_SW_Pin,
                    EncoderUpdatePeriodMs, SwitchUpdatePeriodMs);

    HAL_TIM_Base_Start_IT(&htim6);

    // Initialize display
    INIT_DISPLAY(__Display, &hspi1);
    __Display.setOrientation(Rotation::Degre_90);
    DadGFX::cFont	FontTitre(&__Font_24pb);
    DadGFX::cFont	FontInfo(&__Font_16p);
    DadGFX::cFont	FontInfo1(&__Font_14p);
    DadGFX::cFont FontInfo2(&__Font_12p);
    DadGFX::cFont FontInfo3(&__Font_10p);

    DadGFX::cLayer* pMainLayer  = ADD_LAYER(__Display, MainLayer, 0, 0, 0);  // Create main display layer
    pMainLayer->changeZOrder(3);
    pMainLayer->eraseLayer(DadGFX::sColor(0,0,0,255));

    DadGFX::cLayer* pInfoLayer  = ADD_LAYER(__Display, InfoLayer, 0, Y_INFO_FLASHER, 0);  // Create Info display layer
    pInfoLayer->changeZOrder(10);
    pInfoLayer->eraseLayer();
    pInfoLayer->setFont(&FontInfo);

    DadGFX::cLayer* pBlocInfoLayer  = ADD_LAYER(__Display, BlocInfoLayer, 0, Y_BLOC_FLASHER, 0);  // Create Burn Info display layer
    pBlocInfoLayer->changeZOrder(20);
    pBlocInfoLayer->eraseLayer();
    pBlocInfoLayer->setFont(&FontInfo2);

    DadGFX::cLayer* pTargetLayer  = ADD_LAYER(__Display, TargetLayer, 0, Y_TARGET_LOADER, 0);  // Create Burn Info display layer
    pTargetLayer->changeZOrder(20);
    pTargetLayer->eraseLayer();
    pTargetLayer->setFont(&FontInfo1);

    DadGFX::cLayer* pChoiceLayer  = ADD_LAYER(__Display, ChoiceLayer, 0, Y_CHOICE_LOADER, 0);  // Create Burn Info display layer
    pChoiceLayer->changeZOrder(20);
    pChoiceLayer->eraseLayer();
    pChoiceLayer->setFont(&FontInfo2);

    // -------------------------------------------------------------------
    // Draw Flasher panel
    pMainLayer->drawRect(4, 4, SCREEN_WIDTH - 8, FLASHER_PANEL_HEIGHT, 2,DadGFX::sColor(2, 229, 245));
    const char* Text1 = "Flasher";
    pMainLayer->setFont(&FontTitre);
    uint16_t TextWidth = pMainLayer->getTextWidth(Text1);
    pMainLayer->setCursor((SCREEN_WIDTH - TextWidth)/2, Y_TITRE_FLASHER);
    pMainLayer->setTextFrontColor(DadGFX::sColor(33, 223, 237));
    pMainLayer->drawText(Text1);
    __Display.flush();

    // -------------------------------------------------------------------
    // Draw Loader panel
    pMainLayer->drawRect(4, Y_LOADER_PANEL, SCREEN_WIDTH - 8, LOADER_PANEL_HEIGHT, 2, DadGFX::sColor(2, 229, 245));
    Text1 = "Loader";
    pMainLayer->setFont(&FontTitre);
    TextWidth = pMainLayer->getTextWidth(Text1);
    pMainLayer->setCursor((SCREEN_WIDTH - TextWidth)/2, Y_TITRE_LOADER);
    pMainLayer->setTextFrontColor(DadGFX::sColor(33, 223, 237));
    pMainLayer->drawText(Text1);

    pMainLayer->setFont(&FontInfo3);
    pMainLayer->setTextFrontColor(DadGFX::sColor(252, 252, 242));
    pMainLayer->setCursor(20, Y_HELP_LOADER+10);
    pMainLayer->drawText("Use encoder M to select the ELF file to launch.");
    pMainLayer->setCursor(20, Y_HELP_LOADER+25);
    pMainLayer->drawText("     * Push-> Save");
    pMainLayer->setCursor(20, Y_HELP_LOADER+40);
    pMainLayer->drawText("     * Turn->  Scroll through files");
    __Display.flush();

    // -------------------------------------------------------------------
    // Initialize flasher
    __FlasherClient.Initialize((uint8_t *)&__FlasherStorage);
    DadPersistentStorage::FlasherClientResult   MemResult = DadPersistentStorage::FlasherClientResult::Dummy;
    uint32_t	MemMemory = 50000;
    scanELF_File();
    const char *pTargetName = nullptr;
    uint16_t MemLoaderTarget = DIR_FILE_COUNT+2;
    uint16_t TextHeight;
    uint16_t MemTargetChoice = DIR_FILE_COUNT+1;
    uint16_t TargetChoice = 0;

    while (1){
		// -------------------------------------------------------------------
		// Flasher process
		__FlasherClient.FlasherClientLoop();

		// Draw Info
		DadPersistentStorage::FlasherClientResult   Result = __FlasherClient.getResult();
		if(Result != MemResult){
			const char* pInfoText;
			MemResult = Result;
			// Draw info
			switch (Result){
				case DadPersistentStorage::FlasherClientResult::Wait :
					pInfoText = "Wait flasher server";
					break;
				case DadPersistentStorage::FlasherClientResult::Receve :
					pInfoText = "Receive Blocs";
					break;
				case DadPersistentStorage::FlasherClientResult::EndTrans :
					// Scan ELF files and erase loader target
					scanELF_File();
					__LoaderMemTarget.save(DIR_FILE_COUNT+1);
					MemLoaderTarget = DIR_FILE_COUNT+2;
					MemTargetChoice = DIR_FILE_COUNT+1;
					TargetChoice = 0;
					pInfoText = "Flash OK";
					break;
				case DadPersistentStorage::FlasherClientResult::Error :
				default :
					// Scan ELF files and erase loader target
					__LoaderMemTarget.save(DIR_FILE_COUNT+1);
					MemLoaderTarget = DIR_FILE_COUNT+2;
					MemTargetChoice = DIR_FILE_COUNT+1;
					TargetChoice = 0;
					pInfoText = "/!\\ Error";
					break;
			}
			pInfoLayer->eraseLayer();
			TextWidth = pInfoLayer->getTextWidth(pInfoText);
			TextHeight = pInfoLayer->getTextHeight();
			pInfoLayer->setCursor((SCREEN_WIDTH - TextWidth)/2, TextHeight + 2);
			pInfoLayer->setTextFrontColor(DadGFX::sColor(245, 217, 7));
			pInfoLayer->drawText(pInfoText);
		}

		// Draw burn state
		uint32_t Memory = __FlasherClient.getTotalMemoryTransfered();
		if(MemMemory != Memory){
			char BurnTxt[50];
			uint16_t KOctet = Memory/1024;
			uint16_t  FlashRemaining =  (FLASHER_MEM_SIZE/1024) - KOctet;
			snprintf(BurnTxt, sizeof(BurnTxt), "%d Ko Flashed / %d Ko Free", KOctet, FlashRemaining);
			pBlocInfoLayer->eraseLayer();
			TextWidth = pBlocInfoLayer->getTextWidth(BurnTxt);
			TextHeight = pBlocInfoLayer->getTextHeight();
			pBlocInfoLayer->setCursor((SCREEN_WIDTH - TextWidth)/2, TextHeight + 2);
			pBlocInfoLayer->setTextFrontColor(DadGFX::sColor(245, 217, 7));
			pBlocInfoLayer->drawText(BurnTxt);
		}

		// Draw loader Target
		uint16_t LoaderTarget = __LoaderMemTarget.load();
		if(MemLoaderTarget != LoaderTarget){
			MemLoaderTarget = LoaderTarget;
			pTargetName = __FlasherStorage.GetFileName(LoaderTarget);
			char TargetTxt[50];
			if(pTargetName != nullptr){
				snprintf(TargetTxt, sizeof(TargetTxt), "Target : %s", pTargetName);
			}else{
				snprintf(TargetTxt, sizeof(TargetTxt), "No Loader target");
			}
			pTargetLayer->eraseLayer();
			TextWidth = pTargetLayer->getTextWidth(TargetTxt);
			TextHeight = pTargetLayer->getTextHeight();
			pTargetLayer->setCursor((SCREEN_WIDTH - TextWidth)/2, TextHeight + 2);
			pTargetLayer->setTextFrontColor(DadGFX::sColor(245, 217, 7));
			pTargetLayer->drawText(TargetTxt);
		}

		// Draw loader Target choice
		if(MemTargetChoice != TargetChoice){
			MemTargetChoice = TargetChoice;
			char ChoiceTxt[50];
			if(__NbELF_File != 0){
				const char * pChoiceName = __FlasherStorage.GetFileName(__TabELF_File[TargetChoice]);
				if(pChoiceName != nullptr){
					snprintf(ChoiceTxt, sizeof(ChoiceTxt), "Change to : %s", pChoiceName);
				}else{
					snprintf(ChoiceTxt, sizeof(ChoiceTxt), "No ELF file loaded in flash");
				}
			}else{
				snprintf(ChoiceTxt, sizeof(ChoiceTxt), "No ELF file loaded in flash");
			}
			pChoiceLayer->eraseLayer();
			TextWidth = pChoiceLayer->getTextWidth(ChoiceTxt);
			TextHeight = pChoiceLayer->getTextHeight();
			pChoiceLayer->setCursor((SCREEN_WIDTH - TextWidth)/2, TextHeight + 2);
			pChoiceLayer->setTextFrontColor(DadGFX::sColor(245, 217, 7));
			pChoiceLayer->drawText(ChoiceTxt);
		}

		if(((Result == DadPersistentStorage::FlasherClientResult::EndTrans) ||
			(Result == DadPersistentStorage::FlasherClientResult::Wait)) &&
			(__NbELF_File != 0)){
			int8_t Inc = __Encoder0.getIncrement();
			TargetChoice = (TargetChoice + Inc) % __NbELF_File;
			if((__Encoder0.getSwitchState() == 1) &&
			   (TargetChoice != __LoaderMemTarget.load())){
				__LoaderMemTarget.save(__TabELF_File[TargetChoice]);
			}
		}
		__Display.flush();
    }
}



//***End of file**************************************************************




